version: '2'
services:
  acmecsv-mysql:
    image: mysql:5.7
    volumes:
      - ./volumes/:/var/lib/mysql/
    environment:
      - "MYSQL_USER=root"
      - "MYSQL_ROOT_PASSWORD=test_pwd"
      - "MYSQL_PASSWORD=test_pwd"
      - "MYSQL_DATABASE=acmecsv"
      - "MYSQL_ROOT_HOST=%"
    ports:
      - 3306:3306
    command: mysqld  --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
